server:
  port: 8001
spring:
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database: mysql
    show-sql: true
  servlet:
    multipart:
      max-file-size: 102400MB
      max-request-size: 102400MB

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 4
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1

